version: "3.8"

services:
  backend:
    build: ./backend        # assumes you have a Dockerfile in backend/
    container_name: backend
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/foodstallhub

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foodstallhub
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
